name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]  # Added 3.11
        os: [ubuntu-latest]  # Multi-OS testing capability

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        
    - name: Run tests
      run: |
        cd tests  # Specific test directory
        pytest test_utils.py -v  # Target specific test file
        cd ..
      
    - name: Verify test coverage (optional)
      if: always()
      run: |
        echo "Tests completed for Python ${{ matrix.python-version }}"
        echo "View test results in the Actions tab"
